### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by PaulBGD** [CJKay/bsa#1]
Hi, I noticed your bsa-old repository and was curious if that was archived for a rewrite or something. Is there anything I could assist with?

**Comment by CJKay** [comment]
Hi, thanks for your interest - it's something I had planned on restarting when I got back into Skyrim modding, but I'm afraid the moment passed! Feel free to take the archived version and do whatever you want with it - it was certainly far from complete.

**Comment by PaulBGD** [comment]
Sounds good!
